<script>
  import { scaleLength } from "$lib/support";

  export let width = "100px";
  export let height = "100px";
  export let color = "currentColor";

  let aspectRatio = 1;

  if ($$props.width && !$$props.height) height = scaleLength(width, 1 / aspectRatio);
  if ($$props.height && !$$props.width) width = scaleLength(height, aspectRatio);
</script>

<svg
  {width}
  {height}
  {...$$restProps}
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  viewBox="0 0 100 100"
  preserveAspectRatio="xMidYMid"
>
  <circle
    cx="50"
    cy="50"
    r="32"
    stroke-width="8"
    stroke={color}
    stroke-dasharray="50.26548245743669 50.26548245743669"
    fill="none"
    stroke-linecap="round"
  >
    <animateTransform
      attributeName="transform"
      type="rotate"
      repeatCount="indefinite"
      dur="1s"
      keyTimes="0;1"
      values="0 50 50;360 50 50"
    />
  </circle>
  <!-- [ldio] generated by https://loading.io/ --></svg
>
